import http from 'k6/http';
import { check } from 'k6';
import { apiUrl, requestParams, uniqueSuffix } from './config.js';
import { pick, safeJson } from './checks.js';

export function createCourse(token, label = 'course', metricName = 'Setup_Create_Course', extraTags = {}) {
  const suffix = uniqueSuffix(label);
  const response = http.post(
    apiUrl('/api/courses'),
    JSON.stringify({
      title: `k6 ${label} ${suffix}`,
      theme: 'Performance testing',
      description: `Course generated by k6 scenario ${label}.`,
    }),
    requestParams(metricName, token, {
      endpoint: '/api/courses',
      phase: metricName.startsWith('Setup') ? 'setup' : 'default',
      ...extraTags,
    }),
  );

  const body = safeJson(response);
  const courseId = pick(body, 'id', 'Id');

  check(response, {
    [`${metricName}: status is 201`]: (r) => r.status === 201,
    [`${metricName}: course id returned`]: () => Boolean(courseId),
  });

  return {
    response,
    body,
    courseId,
  };
}

export function createCourseModule(token, courseId, label = 'module', metricName = 'Setup_Create_Module', extraTags = {}) {
  const response = http.post(
    apiUrl(`/api/courses/${courseId}/modules`),
    JSON.stringify({
      title: `k6 ${label}`,
      description: `Module generated by k6 scenario ${label}.`,
    }),
    requestParams(metricName, token, {
      endpoint: '/api/courses/{courseId}/modules',
      phase: metricName.startsWith('Setup') ? 'setup' : 'default',
      ...extraTags,
    }),
  );

  const body = safeJson(response);
  const moduleId = pick(body, 'id', 'Id');

  check(response, {
    [`${metricName}: status is 201`]: (r) => r.status === 201,
    [`${metricName}: module id returned`]: () => Boolean(moduleId),
  });

  return {
    response,
    body,
    moduleId,
  };
}

export function createLesson(token, courseId, moduleId, label = 'lesson', metricName = 'Setup_Create_Lesson', extraTags = {}) {
  const response = http.post(
    apiUrl(`/api/courses/${courseId}/modules/${moduleId}/lessons`),
    JSON.stringify({
      title: `k6 ${label}`,
      content: `Lesson content generated by k6 scenario ${label}.`,
    }),
    requestParams(metricName, token, {
      endpoint: '/api/courses/{courseId}/modules/{moduleId}/lessons',
      phase: metricName.startsWith('Setup') ? 'setup' : 'default',
      ...extraTags,
    }),
  );

  const body = safeJson(response);
  const lessonId = pick(body, 'id', 'Id');

  check(response, {
    [`${metricName}: status is 201`]: (r) => r.status === 201,
    [`${metricName}: lesson id returned`]: () => Boolean(lessonId),
  });

  return {
    response,
    body,
    lessonId,
  };
}

export function createCourseFixture(token, label = 'fixture') {
  const course = createCourse(token, label);

  if (!course.courseId) {
    throw new Error(`Could not create setup course. Status: ${course.response.status}`);
  }

  const module = createCourseModule(token, course.courseId, label);

  if (!module.moduleId) {
    throw new Error(`Could not create setup course module. Status: ${module.response.status}`);
  }

  const lesson = createLesson(token, course.courseId, module.moduleId, label);

  if (!lesson.lessonId) {
    throw new Error(`Could not create setup lesson. Status: ${lesson.response.status}`);
  }

  return {
    courseId: course.courseId,
    moduleId: module.moduleId,
    lessonId: lesson.lessonId,
  };
}
