version: '3.8'

services:
  db:
    image: postgres:18.1
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: lms_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U my_postgres_user -d my_postgres_database"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s

volumes:
  db_data: